version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan serve --host=0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    networks:
      - laravel

networks:
  laravel:
